### ISSUE TITLE
Always getting same Background Color

### ISSUE THREAD

**Issue by hodgesmr** [luisespinoza/LEColorPicker#12]
I was playing with this today and I'm seeing an unexpected result with `pickColorsFromImage:` method. It's always returning a background color of `0.235294 0.278431 0.27451` regardless of the image I pass in. An example of the code I'm doing:

``` objc
[LEColorPicker pickColorFromImage:[UIImage imageNamed:@"img_header.png"] onComplete:^(NSDictionary *colorsPickedDictionary) {
        topView.backgroundColor = [colorsPickedDictionary objectForKey:@"BackgroundColor"];
}];
```

I've tried many different img_headers, but I keep getting this same gray/green color. Am I using this incorrectly?

**Comment by hodgesmr** [comment]
Nevermind. This appears to have been user error.

**Comment by luisespinoza** [comment]
Thanks! :dancers:
