### ISSUE TITLE
Why the need for AppActive ?

### ISSUE THREAD

**Issue by octplane** [luisespinoza/LEColorPicker#6]
colorSchemeFromImage seems to require that the App is Active, but I fail to see why ?

In my very simple test of your nice library, I wanted to customize labels colors in the first view so I'm calling your library in viewDidLoad. Seems that my app wasn't already active and it returned nil.

Bypassing the test seems to give a correct non-crashing behavior.

Am I missing something ?

Thank you very much for your time :)

**Comment by rweichler** [comment]
The library uses the OpenGL library to figure out the colors for the image, so if you call it while the application is backgrounded on a device, it will crash with a  gpus_ReturnNotPermittedKillClient. [See this issue for more information.](https://github.com/luisespinoza/LEColorPicker/issues/5)

**Comment by larsacus** [comment]
I've found that checking for the background state alone is sufficient to avoid a crash.

**Comment by rweichler** [comment]
@larsacus can you elaborate?

**Comment by larsacus** [comment]
The system will indeed crash the app when `gl_` calls are made from the background, but an "inactive" state does not constitute a "backgrounded" state and will permit `gl_` calls. The "inactive" state includes the state during state restoration or during the transition from the background to the foreground before control has been given to the user.

I have a branch that includes this fix as well as several others I've been using in production without issue.

``` lang:objective-c
- (BOOL)isAppActive
{
    UIApplicationState state = [[UIApplication sharedApplication] applicationState];
    if (state == UIApplicationStateBackground)
    {
        return NO;
    }

    return YES;
}
```

**Comment by octplane** [comment]
I'll close the issue as I thing things are better now. Thanks for all :)
