### ISSUE TITLE
Integrate CocoaPods support ?

### ISSUE THREAD

**Issue by octplane** [luisespinoza/LEColorPicker#8]
I don't know if many others here use CocoaPods, but I'd definitely like it if LEColorPicker could be declared as a CocoaPod dependency. This would probably requires splitting this repo between the main lib and the example application, although I'm not sure about that.

What do you think ? I could probably look into that if @luisespinoza agrees and nobody else has more competency on that matter than I do (and for the records, I have none :P)

http://cocoapods.org/

**Comment by octplane** [comment]
HA-ha.

I found out this was already done. But the version is not quite up to date, so maybe a new tagged version here could suffice to update the pod there....

https://github.com/CocoaPods/Specs/blob/master/LEColorPicker/0.1.2/LEColorPicker.podspec

**Comment by luisespinoza** [comment]
I will tag this again, since we have some bugs fixed and improvements. However, I´m not sure if that will trigger the pod update.

**Comment by octplane** [comment]
Nope, but I can try to submit a PR to their repository...

**Comment by luisespinoza** [comment]
Ok, new tag 1.0.1 is ready. I'll be open eyed for anything you need to update the pod.

**Comment by ageorgios** [comment]
+1 for the cocoapods integration

**Comment by octplane** [comment]
https://github.com/CocoaPods/Specs/pull/5161

This should work OK now. If someone can confirm the integration is working as expected. We can close the issue.
